"""Alembic environment.

Migrations run through the same async driver as the application, so there is no
second database driver to install or configure. The URL comes from application
settings (i.e. from DATABASE_URL), never from alembic.ini.
"""

from __future__ import annotations

import asyncio
from logging.config import fileConfig

from alembic import context
from app.core.config import get_settings
from app.db.base import Base
from app.db.models import KnowledgeChunk, KnowledgeDocument
from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

settings = get_settings()
config.set_main_option("sqlalchemy.url", settings.database_url)

# Model imports above ensure Base.metadata contains knowledge tables.
target_metadata = Base.metadata
_ = (KnowledgeDocument, KnowledgeChunk)


_POSTGIS_TABLES = frozenset({"spatial_ref_sys", "geography_columns", "geometry_columns"})


def _include_object(_object, name, type_, _reflected, _compare_to) -> bool:  # type: ignore[no-untyped-def]
    """Keep PostGIS-managed tables out of autogenerated migrations."""
    return not (type_ == "table" and name in _POSTGIS_TABLES)


def run_migrations_offline() -> None:
    context.configure(
        url=settings.database_url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
        include_object=_include_object,
    )
    with context.begin_transaction():
        context.run_migrations()


def _run_migrations(connection: Connection) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        compare_type=True,
        include_object=_include_object,
    )
    with context.begin_transaction():
        context.run_migrations()


async def run_migrations_online() -> None:
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    async with connectable.connect() as connection:
        await connection.run_sync(_run_migrations)
    await connectable.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    asyncio.run(run_migrations_online())
